version: "3"
services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: api
    volumes:
      - .:/var/www/app
      - ./apache.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - 3000:80
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
      --init-file=/data/application/init.sql
    volumes:
      - ./init.sql:/data/application/init.sql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE='laravel'
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
